### ISSUE TITLE
null operand semantics hide changes

### ISSUE THREAD

**Issue by mczepiel** [montagejs/frb#2]
"If any operand is null or undefine, a binding will not emit an update. Thus, if a binding’s source becomes invalid, it does not corrupt its target but waits until a valid replacement becomes available."

This poses a problem when I expect the `null` or `undefined` to get passed along, to deal with the "corruption" at the endpoint.

e.g. In Montage I'd like some default handling for null or undefined src on the Image component but when a binding that had been a valid url becomes null the image never knows.

I have worked around this on a binding by binding basis by capping `a.Potentially.Null.Path || nullPlaceholderValue`

But this gets to be a little painful having to solve it on each binding.

I'd prefer to flip the convention to shield less-resilient objects from undefined/null while expecting objects to be tolerant by default.

**Comment by hthetiot** [comment]
should be fixed
