### ISSUE TITLE
Possible to bind to parentElement's offsetWidth?

### ISSUE THREAD

**Issue by rayshan** [montagejs/frb#46]
In a component definition:

```js
this.addPathChangeListener(
  "_element.parentElement.offsetWidth",
  this,
  "handleResize"
);
```

Will only trigger `this.handleResize()` once. `offsetWidth` is definitely changing by checking this way and resizing viewport:

```js
setInterval((function () {
  console.log(this._element.parentElement.offsetWidth);
}).bind(this), 1000);
```

Is this possible?

**Comment by Stuk** [comment]
Afraid not. FRB replaces properties on objects with getters and setters to observe changes. This is not possible with DOM properties. You may be interested in https://github.com/montagejs/frb/blob/master/dom.js

**Comment by rayshan** [comment]
Thanks Stuart that cleared a lot of stuff up! It was mentioned in the docs but I glanced over it:

> unwrapped: Rather than wrap objects and arrays with observable containers, FRB modifies existing arrays and objects to make them dispatch property and content changes. For objects, this involves installing getters and setters using the ES5 Object.defineProperty method.

I'll play w/ `frb/dom`.

**Comment by kriskowal** [comment]
I’d caution you not to play with frb/dom for real. This could seriously mess up the Montage draw loop. If you want to bind to a computed style property, capture the style property in your will draw or did draw phases and apply it to a property of your component. FRB can then safely bind to the component. The related components will then update the DOM in their latter draw phase.

**Comment by rayshan** [comment]
Thanks @kriskowal. I haven't. Checking for `parentElement.offsetWidth` doesn't work in `willDraw` as it's the parent that is drawing, not the component itself. We can have the parent to tell the children to draw, but then the children aren't "smart". The team discussed briefly on possibly making drawing on parent to auto draw children, but we haven't thought through whether it makes sense or how yet.

**Comment by kriskowal** [comment]
@rayshan Draw dependencies are an important conceptual problem that you’ll definitely need to solve regardless. It might suffice for children to bind a property to their parent and react to changes on that property with a draw request.
